### ISSUE TITLE
Floyd-Worshall doing overtime

### ISSUE THREAD

**Issue by juyoung101** [ksundberg/CS1400#6]
Across two Linux machines, Ubuntu MATE on a RasPi2, and a Windows machine, the Floyd-Warshall algorithm seems to run twice. I noticed this when printing out the values of `mid`. The values would run from 0 to 2703, then begin again at 0 and end the second time it reached 2703. What is curious is that the only operation performed on `mid` is an increment as the post-condition of a `for` loop. I am not sure how it reverts to having a 0 value.

**Comment by ksundberg** [comment]
Once is for units that can only move one space, the other is for units that can move up to 5 spaces.  The adjacency matrices are different.
